name: docs.clades.nextstrain.org
channels:
  - defaults
dependencies:
  - linkify-it-py
  - make
  - myst-parser
  - pip
  - requests
  - sphinx
  - pip:
    - nextstrain-sphinx-theme>=2022.5
    - sphinx-argparse
    - sphinx-autobuild
    - sphinx-markdown-tables
    - sphinx-tabs
