name: docs.clades.nextstrain.org
channels:
  - defaults
dependencies:
  - make
  - recommonmark
  - requests
  - sphinx
  - pip
  - pip:
    - nextstrain-sphinx-theme>=2022.5
    - sphinx-markdown-tables
    - sphinx-argparse
    - sphinx-tabs
    - sphinx-autobuild
